services:
  audio-stream:
    build:
      context: https://github.com/fruitcake514/audioOverIP.git  # Your GitHub repository URL
      dockerfile: Dockerfile
    container_name: audio_stream_server
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - PORT=${PORT:-5000}
      - STREAM_URL=${STREAM_URL:-}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
    restart: always
    volumes:
      - ./config:/app/config.json  # Mount config file as volume to persist changes
    deploy:
      resources:
        limits:
          memory: 1G
