services:
  audio-stream-server:
    build:
      context: https://github.com/fruitcake514/audioOverIP.git  # GitHub URL for your repository
      dockerfile: Dockerfile  # Path to the Dockerfile in the repo
    container_name: audio_stream_server
    ports:
      - "12345:12345"  # Audio streaming port (this one might be fixed depending on your app's needs)
      - "${PORT:-5000}:${PORT:-5000}"  # Web server port, default to 5000 if PORT environment variable is not set
    environment:
      - RTSP_URL=rtsp://your-rtsp-stream-url  # Optional: set RTSP URL if using RTSP stream
      - PORT=${PORT:-5000}  # Set PORT environment variable (defaults to 5000)
    restart: always

  web:
    build:
      context: https://github.com/fruitcake514/audioOverIP.git
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - "${PORT:-5000}:${PORT:-5000}"  # Web server port, default to 5000 if PORT environment variable is not set
    restart: always
    depends_on:
      - audio-stream-server
