version: '3.8'

services:
  audio-stream:
    build:
      context: https://github.com/fruitcake514/audioOverIP.git
      dockerfile: Dockerfile
    container_name: audio_stream_server
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=5000
      - STREAM_URL=""
      - AUDIO_SOURCE=microphone
      - SAMPLE_RATE=44100
      - CHANNELS=1
      - CHUNK_SIZE=1024
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY} # openssl rand -hex 32
      - DEBUG=false
      - HOST=0.0.0.0
    restart: always
    volumes:
      - ./config.json:/app/config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    networks:
      - audio_network

networks:
  audio_network:
    driver: bridge
